# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4968e3cc611eda0c41ab0d734e7f818abc6b528187a59bf68cf5f6e13bcab6e81372d3086e0b8090100ec48b2e0eedfc03ec9016abf08b50310dadd440544761

test:
  secret_key_base: 2b5b622f036612ee7e60dfdf13bed9d4718c3305583dac8676e60e9ed75e996cb20a755127ba5af0a34af1dcd95a67a08ba09cde556b5467d3e2f8f8e4a89573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
